name: Build and test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: build_and_test
    strategy:
      matrix:
        toolchain:
          - 1.75.0 # MSRV
          - 1.81.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run: cargo build --verbose
      - run: cargo clippy -- --deny warnings
      - run: cargo clippy --tests -- --deny warnings
      - run: cargo test

# vim: ts=2 sw=2 expandtab
